/**
 * learning.content 离线内容模板种子（冷启动写入 SQLite learning_content_templates）
 * 运行时工具只读库，不在工具文件内堆题干。
 */

export type ContentTemplateAction =
  | 'generate_quiz'
  | 'explain'
  | 'example_set'
  | 'generate_passage'
  | 'generate_writing_prompt'
  | 'dictation';

export interface ContentTemplateSeed {
  id: string;
  language: 'ja' | 'en' | 'ko';
  action: ContentTemplateAction;
  format?: string | null;
  skillId?: string | null;
  difficulty: number;
  topic?: string | null;
  genre?: string | null;
  sortOrder: number;
  /** JSON 可解析负载，见各 kind */
  payload: Record<string, unknown>;
}

export const LEARNING_CONTENT_TEMPLATE_SEEDS: ContentTemplateSeed[] = [
  // ── JA 自适应选择题（助词） ──
  {
    id: 'tpl_ja_quiz_particle_de',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.particle.ni_vs_de',
    difficulty: 2,
    sortOrder: 1,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的格助词填入括号：',
        content: '明日、友人と駅前のカフェ（　）日本語を勉強します。',
        options: ['で', 'に', 'を', 'へ'],
        correctAnswer: 'で',
        explanation: '「勉強する」为动态行为动作，场所用「で」。',
        testedSkillId: 'jp.particle.ni_vs_de',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_ja_quiz_particle_ni',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.particle.ni_vs_de',
    difficulty: 2,
    sortOrder: 2,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的格助词填入括号：',
        content: '図書館の静かな角（　）辞書が置いてあります。',
        options: ['で', 'に', 'を', 'へ'],
        correctAnswer: 'に',
        explanation: '「置いてある」表示物体的静态存在归着状态，场所用「に」。',
        testedSkillId: 'jp.particle.ni_vs_de',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_ja_quiz_tara',
    language: 'ja',
    action: 'generate_quiz',
    format: 'FILL_IN_BLANK',
    skillId: 'jp.grammar.conditional_tara',
    difficulty: 3,
    sortOrder: 3,
    payload: {
      kind: 'question',
      question: {
        type: 'FILL_IN_BLANK',
        prompt: '将括号中的动词变形为正确的假定形（～たら）：',
        content: '明日、雨が（降る ──►　　　　）、試合は中止です。',
        correctAnswer: '降ったら',
        explanation:
          '动词「降る」（五段动词）的过去式为「降った」，后接「ら」构成假定条件「降ったら」。',
        testedSkillId: 'jp.grammar.conditional_tara',
        difficultyTier: 3,
      },
    },
  },

  // ── EN 自适应选择题 ──
  {
    id: 'tpl_en_quiz_subjunctive_1',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.subjunctive',
    difficulty: 3,
    sortOrder: 1,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的动词形式填入括号（虚拟语气）：',
        content:
          'The professor suggested that each student ( ) an outline before drafting the thesis.',
        options: ['submit', 'submits', 'submitted', 'will submit'],
        correctAnswer: 'submit',
        explanation:
          '在 suggest、insist 等表建议要求的动词后，that 引导的宾语从句谓语需使用虚拟语气 (should) + 动词原形，故用 submit。',
        testedSkillId: 'en.grammar.subjunctive',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_en_quiz_subjunctive_2',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.subjunctive',
    difficulty: 3,
    sortOrder: 2,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的动词形式填入括号（虚拟语气）：',
        content:
          'It is imperative that the emergency medical supplies ( ) immediately to the affected area.',
        options: ['be dispatched', 'is dispatched', 'was dispatched', 'has been dispatched'],
        correctAnswer: 'be dispatched',
        explanation:
          '在 It is imperative that ... 句型中，主语从句谓语需采用 (should) + 动词原形，被动语态为 (should) be dispatched。',
        testedSkillId: 'en.grammar.subjunctive',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_en_quiz_inversion',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.inversion',
    difficulty: 3,
    sortOrder: 3,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的语序完成倒装句：',
        content: 'Hardly ( ) the station when the train began to move.',
        options: ['had he arrived at', 'he had arrived at', 'did he arrive at', 'he arrived at'],
        correctAnswer: 'had he arrived at',
        explanation:
          'Hardly ... when ... 句型中，Hardly 置于句首时主句须部分倒装，且主句动作在先，使用过去完成时 had + 主语 + 过去分词。',
        testedSkillId: 'en.grammar.inversion',
        difficultyTier: 3,
      },
    },
  },

  // ── JA 听写 ──
  {
    id: 'tpl_ja_dict_ka',
    language: 'ja',
    action: 'dictation',
    format: 'LISTENING_DICTATION',
    skillId: 'jp.particle.ka',
    difficulty: 2,
    sortOrder: 1,
    payload: {
      kind: 'dictation',
      item: {
        sourceLesson: '自适应听写 · 终助词',
        speaker: '小野',
        fullJapanese: '李さんは中国人ですか。',
        chinese: '小李是中国人吗？',
        blankPrompt: '听录音，填入句尾疑问助词：',
        clozeDisplay: '李さんは中国人です（　）。',
        targetWord: 'か',
        furiganaHint: 'ka',
        categoryTag: '疑问终助词',
        testedSkillId: 'jp.particle.ka',
        grammarExplanation: '终助词「か」附在句尾表示疑问。',
      },
    },
  },
  {
    id: 'tpl_ja_dict_de',
    language: 'ja',
    action: 'dictation',
    format: 'LISTENING_DICTATION',
    skillId: 'jp.particle.ni_vs_de',
    difficulty: 2,
    sortOrder: 2,
    payload: {
      kind: 'dictation',
      item: {
        sourceLesson: '自适应听写 · 场所格',
        speaker: '王',
        fullJapanese: '昨日の夜、静かなカフェで本を読みました。',
        chinese: '昨天晚上，我在安静的咖啡馆读了书。',
        blankPrompt: '听录音，填入动作发生场所格助词：',
        clozeDisplay: '昨日の夜、静かなカフェ（　）本を読みました。',
        targetWord: 'で',
        furiganaHint: 'de',
        categoryTag: '场所格助词辨析',
        testedSkillId: 'jp.particle.ni_vs_de',
        grammarExplanation: '动态动作发生场所用「で」。',
      },
    },
  },
  {
    id: 'tpl_ja_dict_no',
    language: 'ja',
    action: 'dictation',
    format: 'LISTENING_DICTATION',
    skillId: 'jp.particle.no',
    difficulty: 2,
    sortOrder: 3,
    payload: {
      kind: 'dictation',
      item: {
        sourceLesson: '自适应听写 · 所属格',
        speaker: '李',
        fullJapanese: 'これは日本語の教科書です。',
        chinese: '这是日语教科书。',
        blankPrompt: '听录音，填入名词之间的所属格助词：',
        clozeDisplay: 'これは日本語（　）教科書です。',
        targetWord: 'の',
        furiganaHint: 'no',
        categoryTag: '连体格助词',
        testedSkillId: 'jp.particle.no',
        grammarExplanation: '格助词「の」连接两个名词表示所属。',
      },
    },
  },

  // ── EN 听写 ──
  {
    id: 'tpl_en_dict_an',
    language: 'en',
    action: 'dictation',
    format: 'LISTENING_DICTATION',
    skillId: 'en.grammar.article',
    difficulty: 2,
    sortOrder: 1,
    payload: {
      kind: 'dictation',
      item: {
        sourceLesson: 'Dictation · Articles',
        speaker: 'Narrator',
        fullJapanese: 'She made an unexpected discovery in the archives.',
        chinese: '她在档案中有了意外发现。',
        blankPrompt: '听录音，填入不定冠词：',
        clozeDisplay: 'She made ( ) unexpected discovery in the archives.',
        targetWord: 'an',
        furiganaHint: '/ən/',
        categoryTag: '冠词',
        testedSkillId: 'en.grammar.article',
        grammarExplanation: 'unexpected 以元音音素开头，不定冠词用 an。',
      },
    },
  },
  {
    id: 'tpl_en_dict_with',
    language: 'en',
    action: 'dictation',
    format: 'LISTENING_DICTATION',
    skillId: 'en.vocab.collocation',
    difficulty: 2,
    sortOrder: 2,
    payload: {
      kind: 'dictation',
      item: {
        sourceLesson: 'Dictation · Prepositions',
        speaker: 'Narrator',
        fullJapanese: 'The findings were consistent with previous studies.',
        chinese: '这些发现与先前研究一致。',
        blankPrompt: '听录音，填入固定搭配介词：',
        clozeDisplay: 'The findings were consistent ( ) previous studies.',
        targetWord: 'with',
        furiganaHint: '/wɪð/',
        categoryTag: '介词搭配',
        testedSkillId: 'en.vocab.collocation',
        grammarExplanation: 'consistent with 为固定搭配，表示与……一致。',
      },
    },
  },
  {
    id: 'tpl_en_dict_despite',
    language: 'en',
    action: 'dictation',
    format: 'LISTENING_DICTATION',
    skillId: 'en.grammar.connector',
    difficulty: 2,
    sortOrder: 3,
    payload: {
      kind: 'dictation',
      item: {
        sourceLesson: 'Dictation · Connectors',
        speaker: 'Narrator',
        fullJapanese: 'The proposal was rejected despite strong public support.',
        chinese: '尽管公众大力支持，该提案仍被否决。',
        blankPrompt: '听录音，填入让步介词：',
        clozeDisplay: 'The proposal was rejected ( ) strong public support.',
        targetWord: 'despite',
        furiganaHint: '/dɪˈspaɪt/',
        categoryTag: '连接词',
        testedSkillId: 'en.grammar.connector',
        grammarExplanation: 'despite 后接名词短语表示让步，不可接从句。',
      },
    },
  },

  // ── 例句包 ──
  {
    id: 'tpl_ja_examples_particle',
    language: 'ja',
    action: 'example_set',
    skillId: 'jp.particle.ni_vs_de',
    difficulty: 2,
    topic: '助词与谓语动词搭配',
    sortOrder: 1,
    payload: {
      kind: 'examples',
      examples: [
        {
          sentence: '日曜日、静かなカフェで本を読みます。',
          translation: '星期天在安静的咖啡馆读书。',
          grammarPoint: '格助词「で」表示动作发生的动态场所。',
        },
        {
          sentence: '机の上に日本語の辞書があります。',
          translation: '桌子上有日语词典。',
          grammarPoint: '格助词「に」表示无生命物体的静态存在场所。',
        },
        {
          sentence: '来月、京都へ旅行に行きます。',
          translation: '下个月去京都旅行。',
          grammarPoint: '格助词「へ」(读作e)表示移动动作所朝向的方向。',
        },
      ],
    },
  },
  {
    id: 'tpl_en_examples_subjunctive',
    language: 'en',
    action: 'example_set',
    skillId: 'en.grammar.subjunctive',
    difficulty: 3,
    topic: 'Subjunctive mood',
    sortOrder: 1,
    payload: {
      kind: 'examples',
      examples: [
        {
          sentence: 'The board insisted that the report be revised overnight.',
          translation: '董事会坚持要求连夜修订报告。',
          grammarPoint: 'insist that + (should) + 动词原形。',
        },
        {
          sentence: 'It is essential that every candidate arrive on time.',
          translation: '每位考生准时到达至关重要。',
          grammarPoint: 'It is essential that + 虚拟语气。',
        },
        {
          sentence: 'She suggested that we submit the abstract first.',
          translation: '她建议我们先提交摘要。',
          grammarPoint: 'suggest that + 动词原形。',
        },
      ],
    },
  },

  // ── 讲解大纲 ──
  {
    id: 'tpl_ja_explain_particle',
    language: 'ja',
    action: 'explain',
    skillId: 'jp.particle.ni_vs_de',
    difficulty: 2,
    topic: '助词辨析与易混考点',
    sortOrder: 1,
    payload: {
      kind: 'explain',
      explanation: {
        coreConcept:
          '日语格助词的核心在于区分【作用力发散的动作场所(で)】与【静止归着的存在坐标(に)】。',
        rules: [
          '1. 动态谓语（読む、食べる、勉強する）+ で',
          '2. 静态存在（ある、いる、住む、座る）+ に',
          '3. 趋向移动（行く、来る、帰る）+ に/へ',
        ],
        commonMistakes: [
          '误将「部屋で本がある」用于存在句（正确为：部屋に本がある）',
          '误在动作场所句遗漏「で」',
        ],
        mnemonicTip: '“人在动，就用で；物在立，牢记に；去某地，奔向へ。”',
      },
    },
  },
  {
    id: 'tpl_en_explain_subjunctive',
    language: 'en',
    action: 'explain',
    skillId: 'en.grammar.subjunctive',
    difficulty: 3,
    topic: '虚拟语气',
    sortOrder: 1,
    payload: {
      kind: 'explain',
      explanation: {
        coreConcept:
          '英语虚拟语气在表建议、要求、必要性的从句中，谓语常用 (should) + 动词原形。',
        rules: [
          '1. suggest / insist / demand / order that + (should) + 原形',
          '2. It is essential / imperative / important that + (should) + 原形',
          '3. 被动语态保留 be + 过去分词',
        ],
        commonMistakes: [
          '误用第三人称单数 submits',
          '误用一般过去时 submitted',
        ],
        mnemonicTip: '“建议要求别加 s，原形才是通行证。”',
      },
    },
  },

  // ── 写作题干 ──
  {
    id: 'tpl_ja_write_place',
    language: 'ja',
    action: 'generate_writing_prompt',
    format: 'WRITING_PROMPT',
    skillId: 'jp.particle.ni_vs_de',
    difficulty: 2,
    genre: 'translation',
    sortOrder: 1,
    payload: {
      kind: 'writing',
      prompt: {
        category: '日文长句翻译 · 动作场所',
        chinesePrompt: '昨天下午，我和朋友在咖啡馆读了日语书。',
        contextHint: '考查点：伴随助词「と」、动作场所助词「で」、宾格助词「を」及过去时态',
        testedSkillId: 'jp.particle.ni_vs_de',
        standardAnswer: '昨日、友達とカフェで日本語の本を読みました。',
        grammarFocus: '区分动作发生场所「で」与静态存在场所「に」',
      },
    },
  },
  {
    id: 'tpl_ja_write_tara',
    language: 'ja',
    action: 'generate_writing_prompt',
    format: 'WRITING_PROMPT',
    skillId: 'jp.grammar.conditional_tara',
    difficulty: 3,
    genre: 'translation',
    sortOrder: 2,
    payload: {
      kind: 'writing',
      prompt: {
        category: '日文句型运用 · 条件假定',
        chinesePrompt: '明天要是下雨的话，我们就不去公园了。',
        contextHint: '考查点：动词过去式接「ら」构成假定「降ったら」，否定形式「行かない」',
        testedSkillId: 'jp.grammar.conditional_tara',
        standardAnswer: '明日雨が降ったら、公園へ行きません。',
        grammarFocus: '动词假定形「～たら」的自然运用',
      },
    },
  },
  {
    id: 'tpl_ja_write_keigo',
    language: 'ja',
    action: 'generate_writing_prompt',
    format: 'WRITING_PROMPT',
    skillId: 'jp.keigo.self_introduction',
    difficulty: 2,
    genre: 'email',
    sortOrder: 3,
    payload: {
      kind: 'writing',
      prompt: {
        category: '商务日文会话 · 敬语身份',
        chinesePrompt: '初次见面，我是 JC 策划的员工小野，请多关照。',
        contextHint: '考查点：初次会面寒暄、所属助词「の」与郑重敬语',
        testedSkillId: 'jp.keigo.self_introduction',
        standardAnswer: '初めまして、JC企画の社員の小野です。よろしくお願いします。',
        grammarFocus: '初次会面身份介绍与敬语寒暄',
      },
    },
  },
  {
    id: 'tpl_ja_write_reason',
    language: 'ja',
    action: 'generate_writing_prompt',
    format: 'WRITING_PROMPT',
    skillId: 'jp.grammar.reason_kara',
    difficulty: 2,
    genre: 'news_response',
    sortOrder: 4,
    payload: {
      kind: 'writing',
      prompt: {
        category: '读后续写 · 观点表达',
        chinesePrompt: '请用日语简要说明：你为什么坚持每天复习闪卡？',
        contextHint: '考查点：理由表达「～から／～ので」、简体与敬体选择',
        testedSkillId: 'jp.grammar.reason_kara',
        standardAnswer: '毎日フラッシュカードを復習すると、忘れにくくなるからです。',
        grammarFocus: '因果连接与自然收束',
      },
    },
  },
  {
    id: 'tpl_en_write_subjunctive',
    language: 'en',
    action: 'generate_writing_prompt',
    format: 'WRITING_PROMPT',
    skillId: 'en.grammar.subjunctive',
    difficulty: 3,
    genre: 'translation',
    sortOrder: 1,
    payload: {
      kind: 'writing',
      prompt: {
        category: '英译中 · 虚拟语气',
        chinesePrompt: '请用英语写出：委员会要求立刻实施新的安全规章。',
        contextHint: '考查 insist / require that + (should) + 原形',
        testedSkillId: 'en.grammar.subjunctive',
        standardAnswer:
          'The committee insisted that the new safety regulations be put into effect immediately.',
        grammarFocus: '宾语从句虚拟语气与被动语态',
      },
    },
  },
  {
    id: 'tpl_en_write_inversion',
    language: 'en',
    action: 'generate_writing_prompt',
    format: 'WRITING_PROMPT',
    skillId: 'en.grammar.inversion',
    difficulty: 3,
    genre: 'translation',
    sortOrder: 2,
    payload: {
      kind: 'writing',
      prompt: {
        category: '英译中 · 部分倒装',
        chinesePrompt: '请用 Not only 开头改写：他通过了考试，还拿到了全省最高分。',
        contextHint: '考查 Not only 句首倒装',
        testedSkillId: 'en.grammar.inversion',
        standardAnswer:
          'Not only did he pass the challenging exam, but he also achieved the highest score in the province.',
        grammarFocus: '否定副词前置的部分倒装',
      },
    },
  },

  // ── 短文草稿模板（占位符 {{topic}} / {{difficulty}}） ──
  {
    id: 'tpl_ja_passage_default',
    language: 'ja',
    action: 'generate_passage',
    difficulty: 2,
    topic: '日常生活',
    sortOrder: 1,
    payload: {
      kind: 'passage',
      titleTemplate: '「{{topic}}」に関する短い文章',
      bodyTemplate:
        'これは難度 Lv.{{difficulty}} の「{{topic}}」に関する練習用短文です。キーワードと助詞の使い方に注目してください。',
    },
  },
  {
    id: 'tpl_en_passage_default',
    language: 'en',
    action: 'generate_passage',
    difficulty: 2,
    topic: 'daily life',
    sortOrder: 1,
    payload: {
      kind: 'passage',
      titleTemplate: 'A Short Passage on {{topic}}',
      bodyTemplate:
        'This is a level-{{difficulty}} practice passage about {{topic}}. Students should focus on main ideas and key vocabulary.',
    },
  },

  // ── KO TOPIK 骨架示范题 ──
  {
    id: 'tpl_ko_quiz_particle_eso',
    language: 'ko',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    sortOrder: 1,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '빈칸에 알맞은 조사를 고르세요:',
        content: '친구와 카페( ) 한국어를 공부합니다.',
        options: ['에서', '에', '을', '와'],
        correctAnswer: '에서',
        explanation: '동작이 일어나는 장소에는 조사 「에서」를 씁니다.',
        testedSkillId: 'ko.grammar.particle_eseo',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_ko_quiz_particle_e',
    language: 'ko',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    sortOrder: 2,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '빈칸에 알맞은 조사를 고르세요:',
        content: '책상 위( ) 사전이 있습니다.',
        options: ['에', '에서', '을', '로'],
        correctAnswer: '에',
        explanation: '존재의 장소에는 조사 「에」를 씁니다.',
        testedSkillId: 'ko.grammar.particle_eseo',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_ko_explain_particle',
    language: 'ko',
    action: 'explain',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    topic: '조사 에/에서',
    sortOrder: 1,
    payload: {
      kind: 'explain',
      explanation: {
        coreConcept: '한국어 장소 조사의 핵심은 【동작 장소(에서)】와 【존재 위치(에)】를 구분하는 것입니다.',
        rules: ['1. 공부하다/먹다 등 동작 + 에서', '2. 있다/없다 등 존재 + 에', '3. 가다/오다 방향 + 에/로'],
        commonMistakes: ['「카페에 공부합니다」처럼 동작에 에를 쓰는 오류', '존재문에 에서를 쓰는 오류'],
        mnemonicTip: '움직이면 에서, 가만히 있으면 에.',
      },
    },
  },
  {
    id: 'tpl_ko_examples_particle',
    language: 'ko',
    action: 'example_set',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    topic: '조사 에/에서',
    sortOrder: 1,
    payload: {
      kind: 'examples',
      examples: [
        { sentence: '도서관에서 책을 읽어요.', translation: '도서관에서 책을 읽습니다.', grammarPoint: '동작 장소: 에서' },
        { sentence: '가방에 책이 있어요.', translation: '가방 안에 책이 있습니다.', grammarPoint: '존재 장소: 에' },
        { sentence: '학교에 가요.', translation: '학교로 갑니다.', grammarPoint: '이동 목적지: 에' },
      ],
    },
  },
  {
    id: 'tpl_ko_passage_default',
    language: 'ko',
    action: 'generate_passage',
    difficulty: 2,
    topic: '일상생활',
    sortOrder: 1,
    payload: {
      kind: 'passage',
      titleTemplate: '{{topic}}에 관한 짧은 글',
      bodyTemplate: '이것은 난이도 Lv.{{difficulty}}의 「{{topic}}」 연습용 짧은 글입니다. 조사와 핵심 어휘에 주목하세요.',
    },
  },
  {
    id: 'tpl_ko_write_place',
    language: 'ko',
    action: 'generate_writing_prompt',
    format: 'WRITING_PROMPT',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    genre: 'translation',
    sortOrder: 1,
    payload: {
      kind: 'writing',
      prompt: {
        category: '한중 번역 · 장소 조사',
        chinesePrompt: '昨天下午，我和朋友在咖啡馆学了韩语。',
        contextHint: '조사 와/과, 에서, 을/를 및 과거형',
        testedSkillId: 'ko.grammar.particle_eseo',
        standardAnswer: '어제 오후에 친구와 카페에서 한국어를 공부했습니다.',
        grammarFocus: '동작 장소 에서와 목적어 을/를',
      },
    },
  },

  // ── 阶段测评审校题（assessment 蓝图现货；答案确定、范围可验证） ──
  {
    id: 'tpl_assess_ja_ka',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.particle.ka',
    difficulty: 2,
    sortOrder: 11,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的助词填入括号（疑问）：',
        content: 'あした、雨が降る（　）分かりません。',
        options: ['か', 'に', 'を', 'が'],
        correctAnswer: 'か',
        explanation: '句尾表疑问用「か」；这里是“下不下雨不知道”的间接疑问。',
        testedSkillId: 'jp.particle.ka',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ja_no',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.particle.no',
    difficulty: 2,
    sortOrder: 12,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的助词填入括号（领格）：',
        content: 'これは私（　）本です。',
        options: ['の', 'に', 'で', 'を'],
        correctAnswer: 'の',
        explanation: '“我的书”名词连名词用领格「の」，不能省略。',
        testedSkillId: 'jp.particle.no',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ja_dest',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.particle.destination_ni',
    difficulty: 2,
    sortOrder: 13,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的助词填入括号（移动目的地）：',
        content: '来週、家族と京都（　）行きます。',
        options: ['に', 'で', 'を', 'から'],
        correctAnswer: 'に',
        explanation: '移动动词「行く」的去处用「に」；交通工具才用「で」。',
        testedSkillId: 'jp.particle.destination_ni',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ja_kara_1',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.grammar.reason_kara',
    difficulty: 2,
    sortOrder: 14,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的接续助词填入括号（原因）：',
        content: '雨が降る（　）、行きません。',
        options: ['から', 'まで', 'より', 'ほど'],
        correctAnswer: 'から',
        explanation: '“因为下雨所以不去”，原因用「から」，前面是普通形。',
        testedSkillId: 'jp.grammar.reason_kara',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ja_kara_2',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.grammar.reason_kara',
    difficulty: 2,
    sortOrder: 15,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的接续助词填入括号（原因）：',
        content: '安い（　）、これを買います。',
        options: ['から', 'ので', 'のに', 'たら'],
        correctAnswer: 'から',
        explanation: '一类形容词直接加「から」；N5 先只用から表原因。',
        testedSkillId: 'jp.grammar.reason_kara',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ja_keigo_1',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.keigo.self_introduction',
    difficulty: 2,
    sortOrder: 16,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最得体的自我介绍说法：',
        content: 'はじめまして。私は田中（　）。',
        options: ['と申します', 'と言います', 'と話します', 'を申します'],
        correctAnswer: 'と申します',
        explanation: '自称用自谦语「と申します」；对自己不加さん。',
        testedSkillId: 'jp.keigo.self_introduction',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ja_keigo_2',
    language: 'ja',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'jp.keigo.self_introduction',
    difficulty: 2,
    sortOrder: 17,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的敬语填入括号：',
        content: 'よろしくお（　）します。',
        options: ['願い', '祈り', '頼み', '望み'],
        correctAnswer: '願い',
        explanation: '固定搭配「お願いします」（请多关照）。',
        testedSkillId: 'jp.keigo.self_introduction',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ja_tara_neg',
    language: 'ja',
    action: 'generate_quiz',
    format: 'FILL_IN_BLANK',
    skillId: 'jp.grammar.conditional_tara',
    difficulty: 3,
    sortOrder: 18,
    payload: {
      kind: 'question',
      question: {
        type: 'FILL_IN_BLANK',
        prompt: '将括号中的词变形为假定形（～たら）：',
        content: '時間がない（　　）、タクシーで行きます。',
        correctAnswer: 'なかったら',
        explanation: '「ない」的た形是「なかった」，再加「ら」即「なかったら」。',
        testedSkillId: 'jp.grammar.conditional_tara',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_assess_ja_tara_adj',
    language: 'ja',
    action: 'generate_quiz',
    format: 'FILL_IN_BLANK',
    skillId: 'jp.grammar.conditional_tara',
    difficulty: 3,
    sortOrder: 19,
    payload: {
      kind: 'question',
      question: {
        type: 'FILL_IN_BLANK',
        prompt: '将括号中的一类形容词变形为假定形（～たら）：',
        content: 'このかばんは（高い ──►　　　　）、買いません。',
        correctAnswer: '高かったら',
        explanation: '一类形容词：词尾「い」→「かった」+「ら」。',
        testedSkillId: 'jp.grammar.conditional_tara',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_assess_en_subj_3',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.subjunctive',
    difficulty: 3,
    sortOrder: 11,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的动词形式填入括号（虚拟语气）：',
        content: 'The doctor suggested that he ( ) smoking immediately.',
        options: ['quit', 'quits', 'quitted', 'will quit'],
        correctAnswer: 'quit',
        explanation: 'suggest that … 后接 (should) + 动词原形，故用 quit。',
        testedSkillId: 'en.grammar.subjunctive',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_assess_en_subj_4',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.subjunctive',
    difficulty: 3,
    sortOrder: 12,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的动词形式填入括号（虚拟语气）：',
        content: 'I wish I ( ) speak Japanese fluently.',
        options: ['could', 'can', 'will', 'shall'],
        correctAnswer: 'could',
        explanation: 'wish 后接与现在事实相反的虚拟语气，can 的过去式 could 表“本可以却不能”。',
        testedSkillId: 'en.grammar.subjunctive',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_assess_en_subj_5',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.subjunctive',
    difficulty: 3,
    sortOrder: 13,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的动词形式填入括号（虚拟语气）：',
        content: 'It is essential that every student ( ) his own opinion.',
        options: ['express', 'expresses', 'expressed', 'will express'],
        correctAnswer: 'express',
        explanation: 'It is essential that … 后接 (should) + 动词原形，故用 express。',
        testedSkillId: 'en.grammar.subjunctive',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_assess_en_inv_2',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.inversion',
    difficulty: 3,
    sortOrder: 14,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的语序完成倒装句：',
        content: 'Not only ( ) late, but he also forgot the documents.',
        options: ['was he', 'he was', 'is he', 'he is'],
        correctAnswer: 'was he',
        explanation: 'Not only 置于句首时主句部分倒装；描述过去的事，用 was + 主语语序。',
        testedSkillId: 'en.grammar.inversion',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_assess_en_inv_3',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.inversion',
    difficulty: 3,
    sortOrder: 15,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的语序完成倒装句：',
        content: 'Never ( ) such a beautiful sunset before.',
        options: ['have I seen', 'I have seen', 'I saw', 'did I saw'],
        correctAnswer: 'have I seen',
        explanation: 'Never 置于句首引发部分倒装；before 配合现在完成时 have + 主语 + 过去分词。',
        testedSkillId: 'en.grammar.inversion',
        difficultyTier: 3,
      },
    },
  },
  {
    id: 'tpl_assess_en_art_1',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.article',
    difficulty: 2,
    sortOrder: 16,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的冠词填入括号：',
        content: 'She plays ( ) piano very well.',
        options: ['the', 'a', 'an', '—（不用冠词）'],
        correctAnswer: 'the',
        explanation: '乐器前用定冠词 the：play the piano。',
        testedSkillId: 'en.grammar.article',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_en_art_2',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.article',
    difficulty: 2,
    sortOrder: 17,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的冠词填入括号：',
        content: 'I saw ( ) interesting movie yesterday.',
        options: ['an', 'a', 'the', '—（不用冠词）'],
        correctAnswer: 'an',
        explanation: '首次提到的可数名词单数，且后接元音开头，用 an。',
        testedSkillId: 'en.grammar.article',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_en_art_3',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.article',
    difficulty: 2,
    sortOrder: 18,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的冠词填入括号：',
        content: 'He is ( ) honest man.',
        options: ['an', 'a', 'the', '—（不用冠词）'],
        correctAnswer: 'an',
        explanation: 'honest 首字母 h 不发音，按元音处理，用 an。',
        testedSkillId: 'en.grammar.article',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_en_art_4',
    language: 'en',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'en.grammar.article',
    difficulty: 2,
    sortOrder: 19,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '选择最恰当的冠词填入括号：',
        content: "Let's meet at ( ) same place as yesterday.",
        options: ['the', 'a', 'an', '—（不用冠词）'],
        correctAnswer: 'the',
        explanation: 'same 前固定用定冠词 the。',
        testedSkillId: 'en.grammar.article',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ko_eseo_3',
    language: 'ko',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    sortOrder: 11,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '빈칸에 알맞은 조사를 고르세요（动作场所）：',
        content: '친구와 카페( ) 한국어를 공부합니다.',
        options: ['에서', '에', '을', '와'],
        correctAnswer: '에서',
        explanation: '동작이 일어나는 장소에는 「에서」를 씁니다（动作场所用 에서）。',
        testedSkillId: 'ko.grammar.particle_eseo',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ko_eseo_4',
    language: 'ko',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    sortOrder: 12,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '빈칸에 알맞은 조사를 고르세요（存在场所）：',
        content: '고양이가 방( ) 있어요.',
        options: ['에', '에서', '를', '와'],
        correctAnswer: '에',
        explanation: '静态存在场所用 에；只有发生动作才用 에서。',
        testedSkillId: 'ko.grammar.particle_eseo',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ko_eseo_5',
    language: 'ko',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    sortOrder: 13,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '빈칸에 알맞은 조사를 고르세요（目的地）：',
        content: '내일 학교( ) 가요.',
        options: ['에', '에서', '를', '으로'],
        correctAnswer: '에',
        explanation: '移动目的地用 에；动作场所才用 에서。',
        testedSkillId: 'ko.grammar.particle_eseo',
        difficultyTier: 2,
      },
    },
  },
  {
    id: 'tpl_assess_ko_eseo_6',
    language: 'ko',
    action: 'generate_quiz',
    format: 'MULTIPLE_CHOICE',
    skillId: 'ko.grammar.particle_eseo',
    difficulty: 2,
    sortOrder: 14,
    payload: {
      kind: 'question',
      question: {
        type: 'MULTIPLE_CHOICE',
        prompt: '빈칸에 알맞은 조사를 고르세요（动作场所）：',
        content: '도서관( ) 책을 읽어요.',
        options: ['에서', '에', '를', '랑'],
        correctAnswer: '에서',
        explanation: '读书是动作，场所用 에서。',
        testedSkillId: 'ko.grammar.particle_eseo',
        difficultyTier: 2,
      },
    },
  },
];
