import type { KanaRowGuideContent } from '../kana-row-guide-types.js';

/** 平假名基础各行的轻量讲义；详细单字讲解仍来自 curriculum_kana。 */
export const HIRAGANA_ROW_GUIDES: Readonly<Record<string, KanaRowGuideContent>> = {
  あ行: {
    title: '先把五个元音站稳',
    summary: 'あ行不是普通的一行，它就是日语五个基础元音的起点。',
    memoryTip: '把 あ (a)、い (i)、う (u)、え (e)、お (o) 当成五个固定插座，后面的辅音家族都会来这里接电。',
    pronunciationTip: '五个元音短、清楚、不要拖长；う (u) 不要过度撅嘴，先听音再模仿。',
    confusions: ['あ (a) / お (o)', 'え (e) / い (i)', 'お (o) / を (o)'],
    examples: [
      { word: 'あお', reading: 'ao', meaning: '蓝色' },
      { word: 'いえ', reading: 'ie', meaning: '家' },
      { word: 'うえ', reading: 'ue', meaning: '上面' },
      { word: 'えき', reading: 'eki', meaning: '车站' },
      { word: 'おと', reading: 'oto', meaning: '声音' },
    ],
  },
  か行: {
    title: 'k 家族来报到',
    summary: 'か行是最适合拿来理解规律的一行：k 加上五个元音，就得到 ka、ki、ku、ke、ko。',
    memoryTip: '先顺着念 `ka-ki-ku-ke-ko`，再立刻打乱。き (ki) 和さ (sa) 要并排看，く (ku) 和片假名ク (ku) 要分清字形。',
    pronunciationTip: 'k 要轻、短，不要在后面额外拖出一个中文声调。',
    confusions: ['き (ki) / さ (sa)', 'く (ku) / ク (ku)', 'け (ke) / は (ha)'],
    examples: [
      { word: 'かお', reading: 'kao', meaning: '脸' },
      { word: 'き', reading: 'ki', meaning: '树' },
      { word: 'くち', reading: 'kuchi', meaning: '嘴' },
      { word: 'けさ', reading: 'kesa', meaning: '今天早上' },
      { word: 'こえ', reading: 'koe', meaning: '声音' },
    ],
  },
  さ行: {
    title: 's 家族里藏着一个 shi',
    summary: 'さ行大体是 sa、shi、su、se、so，第二个位置不要机械写成 si。',
    memoryTip: 'さ (sa) 和き (ki) 对着记；し (shi) 和つ (tsu) 对着听，不要只看一眼形状就下结论。',
    pronunciationTip: 'し (shi) 是连续的摩擦音，す (su) 先按清楚的 su 练，弱化是以后遇到自然语流再处理。',
    confusions: ['さ (sa) / き (ki)', 'し (shi) / つ (tsu)', 'そ (so) / ん (n)'],
    examples: [
      { word: 'さかな', reading: 'sakana', meaning: '鱼' },
      { word: 'しお', reading: 'shio', meaning: '盐' },
      { word: 'すし', reading: 'sushi', meaning: '寿司' },
      { word: 'せんせい', reading: 'sensei', meaning: '老师' },
      { word: 'そら', reading: 'sora', meaning: '天空' },
    ],
  },
  た行: {
    title: 't 家族有两个小变身',
    summary: 'た行是 ta、chi、tsu、te、to；ち (chi) 和つ (tsu) 是这里的重点。',
    memoryTip: '看到 ち (chi) 不要脑补 ti，看到 つ (tsu) 也不要脑补 tu。把 し (shi) / つ (tsu) 放在一张对比卡里。',
    pronunciationTip: 'ち (chi) 带有 ch 的起音，つ (tsu) 是 ts 的组合；先模仿整拍，不要拆成两个字母音。',
    confusions: ['ち (chi) / さ (sa)', 'つ (tsu) / し (shi)', 'て (te) / く (ku)'],
    examples: [
      { word: 'たまご', reading: 'tamago', meaning: '鸡蛋' },
      { word: 'ちず', reading: 'chizu', meaning: '地图' },
      { word: 'つき', reading: 'tsuki', meaning: '月亮' },
      { word: 'て', reading: 'te', meaning: '手' },
      { word: 'とけい', reading: 'tokei', meaning: '钟表' },
    ],
  },
  な行: {
    title: 'n 家族：先把三兄弟认清',
    summary: 'な行的读音规律很稳定，真正调皮的是字形：ぬ (nu)、め (me)、ね (ne) 很容易撞脸。',
    memoryTip: 'な (na)、に (ni)、ぬ (nu)、ね (ne)、の (no) 先按 n 加元音理解，再把 ぬ/め/ね、ね/れ/わ 放在一起练。',
    pronunciationTip: 'n 先按短促清楚的鼻音练；ん (n) 不是这一行的第六个孩子，它要单独学。',
    confusions: ['ぬ (nu) / め (me) / ね (ne)', 'ね (ne) / れ (re) / わ (wa)', 'の (no) / そ (so)'],
    examples: [
      { word: 'なつ', reading: 'natsu', meaning: '夏天' },
      { word: 'にほん', reading: 'nihon', meaning: '日本' },
      { word: 'ぬの', reading: 'nuno', meaning: '布' },
      { word: 'ねこ', reading: 'neko', meaning: '猫' },
      { word: 'のり', reading: 'nori', meaning: '海苔/胶水（视语境）' },
    ],
  },
  は行: {
    title: 'h 家族，ふ (fu) 要特别听',
    summary: 'は行通常记作 ha、hi、fu、he、ho；ふ (fu) 不要被英语 hu 或中文“夫”带跑。',
    memoryTip: 'は (ha) / ほ (ho) 并排看，は (ha) / ば (ba) / ぱ (pa) 留到浊音章节做三联对比。',
    pronunciationTip: 'ふ (fu) 更接近双唇轻触后的摩擦送气，先听系统音频，不要用中文谐音永久代替。',
    confusions: ['は (ha) / ほ (ho)', 'ふ (fu) / う (u)', 'は (ha) / ば (ba) / ぱ (pa)'],
    examples: [
      { word: 'はな', reading: 'hana', meaning: '花' },
      { word: 'ひと', reading: 'hito', meaning: '人' },
      { word: 'ふね', reading: 'fune', meaning: '船' },
      { word: 'へや', reading: 'heya', meaning: '房间' },
      { word: 'ほし', reading: 'hoshi', meaning: '星星' },
    ],
  },
  ま行: {
    title: 'm 家族：用重复词加深印象',
    summary: 'ま行的声音比较规整，很适合用短词和重复词把字形钉住。',
    memoryTip: 'め (me) 和ぬ (nu) 并排看；みみ (mimi)、もも (momo) 这种重复词能让同一个字形多出现一次。',
    pronunciationTip: 'm 是双唇起音，保持一拍，不要把词里的每个假名读得忽快忽慢。',
    confusions: ['め (me) / ぬ (nu)', 'む (mu) / ほ (ho)', 'も (mo) / ま (ma)'],
    examples: [
      { word: 'まど', reading: 'mado', meaning: '窗户' },
      { word: 'みみ', reading: 'mimi', meaning: '耳朵' },
      { word: 'むし', reading: 'mushi', meaning: '虫' },
      { word: 'め', reading: 'me', meaning: '眼睛' },
      { word: 'もも', reading: 'momo', meaning: '桃子' },
    ],
  },
  や行: {
    title: 'y 家族只有三个成员',
    summary: 'や行现代基础表只有 や (ya)、ゆ (yu)、よ (yo)，没有独立的 yi、ye。',
    memoryTip: '先把三字认熟，再认识小ゃ (ya)、ゅ (yu)、ょ (yo)；小字一出现，就可能要和前一个假名合体。',
    pronunciationTip: 'ゆ (yu) 不要直接套英语 you，按日语短元音听和读。',
    confusions: ['や (ya) / か (ka)', 'ゆ (yu) / こ (ko)', 'よ (yo) / ま (ma)'],
    examples: [
      { word: 'やま', reading: 'yama', meaning: '山' },
      { word: 'ゆめ', reading: 'yume', meaning: '梦' },
      { word: 'よる', reading: 'yoru', meaning: '夜晚' },
      { word: 'やさい', reading: 'yasai', meaning: '蔬菜' },
    ],
  },
  ら行: {
    title: 'r 家族：舌尖轻弹一下',
    summary: 'ら行的罗马字写成 r，但实际发音不是英语 r，也不是汉语 l。',
    memoryTip: '先记清五个元音结尾，再用 る (ru)/ろ (ro)、れ (re)/ね (ne)/わ (wa) 做形状对比。',
    pronunciationTip: '舌尖在齿龈附近轻轻碰一下，短、轻、不要卷舌；能听出来比纠结它到底像 r 还是 l 更重要。',
    confusions: ['る (ru) / ろ (ro)', 'れ (re) / ね (ne) / わ (wa)', 'り (ri) / い (i)'],
    examples: [
      { word: 'らいげつ', reading: 'raigetsu', meaning: '下个月' },
      { word: 'りんご', reading: 'ringo', meaning: '苹果' },
      { word: 'るす', reading: 'rusu', meaning: '不在家' },
      { word: 'れきし', reading: 'rekishi', meaning: '历史' },
      { word: 'ろく', reading: 'roku', meaning: '六' },
    ],
  },
  わ行: {
    title: 'わ行：成员不多，但を会换读法',
    summary: '现代基础表主要留下 わ (wa) 和 を (o)，另有单独的 ん (n) 收尾。',
    memoryTip: 'わ (wa) 和ね (ne)/れ (re) 成组看；を (o) 字形单独记，但在助词中通常读 o。',
    pronunciationTip: 'を (o) 不要因为历史罗马字写作 wo 就读成两个音；先按现代标准语的 o 练。',
    confusions: ['わ (wa) / ね (ne) / れ (re)', 'を (o) / お (o)', 'ん (n) / そ (so)'],
    examples: [
      { word: 'わたし', reading: 'watashi', meaning: '我' },
      { word: 'わかる', reading: 'wakaru', meaning: '明白' },
      { word: 'みずを', reading: 'mizu o', meaning: '水（宾语）' },
      { word: 'ほん', reading: 'hon', meaning: '书' },
    ],
  },
  特殊: {
    title: 'ん (n)：没有元音的特殊拍',
    summary: 'ん (n) 不属于 na、ni、nu、ne、no 的普通排列，它是一个独立的鼻音拍。',
    memoryTip: '把 ん (n) 当成“鼻音收尾”，不要给它偷偷加上 a、i、u、e 或 o。',
    pronunciationTip: '具体听感会受后面的音影响，入门先做到不加元音、占一拍即可。',
    confusions: ['ん (n) / そ (so)', 'ん (n) / ソ (so)', 'ん (n) / な (na)'],
    examples: [
      { word: 'ほん', reading: 'hon', meaning: '书' },
      { word: 'さん', reading: 'san', meaning: '三/称呼' },
      { word: 'にほん', reading: 'nihon', meaning: '日本' },
      { word: 'さんぽ', reading: 'sanpo', meaning: '散步' },
    ],
  },
};
